// 어려운 용어를 "중학생도 이해할 수준"으로 풀어 쓴 사전 (6개 언어).
// key는 화면 곳곳의 <Term k="..."> 와 매칭된다.
// GLOSSARY[lang][key] = { title, body }. lang은 i18n 컨텍스트에서 받는다.
export const GLOSSARY = {
  en: {
    score: { title: 'Buy-Timing Score', body: 'A 0–100 score made by combining the 6 indicators below. Higher means "a relatively OK time to buy"; lower means "overheated, risky to buy." It is not a prediction of the future, just a composite reference.' },
    RSI: { title: 'RSI · Relative Strength Index', body: 'Shows on a 0–100 scale whether the price rose or fell too fast recently. Below 30 = "fell too much (oversold)", so a bounce is expected — worth watching to buy. Above 70 = "rose too much (overbought)" — be careful.' },
    MACD: { title: 'MACD · Trend Momentum', body: 'Uses the gap between a short and a long moving average to gauge whether upward "force" is strengthening or weakening. When the bars turn up from negative, it is read as a bounce starting from the bottom.' },
    FNG: { title: 'Fear & Greed Index', body: 'Measures on a 0–100 scale whether investors are scared (fear) or greedy (greed). Near 0 everyone is panic-selling — often the cheap buying chance (contrarian). Near 100 means overheated.' },
    Mayer: { title: 'Mayer Multiple', body: 'How many times the current price is versus the "200-day average price." Below 1 = cheaper than average; below 0.8 = historically a bottom zone (strong buy); above 2.4 = overheated/expensive.' },
    DD: { title: 'Drawdown · Drop from the High', body: 'How many % the price is down from the highest point of the last year. -50% means it halved from the top. The bigger the drop, the more it is seen as a fear phase and a staged-buying chance.' },
    GC_DC: { title: 'Golden / Death Cross', body: 'When the short average (50d) crosses above the long average (200d) it is a golden cross (uptrend starts); crossing below is a death cross (downtrend). It shows whether the big trend points up or down.' },
    mcap: { title: 'Market Cap', body: 'The total market value of the coin. Calculated as current price × coins in circulation. It shows how big the coin is in the market.' },
    vol: { title: 'Volume (24h)', body: 'The total amount traded over the last 24 hours. The higher it is, the more active the interest and trading.' },
    chg24: { title: '24h Change', body: 'How many % the price rose (green) or fell (red) compared with a day ago.' },
    stale: { title: 'STALE · Old Data', body: 'A flag meaning the fetched data is too old to be fresh. Hit refresh (↻) to update to the latest.' },
    coverage: { title: 'Indicator Coverage', body: 'How many of the 6 indicators are actually live when computing the score. 6/6 means all are used; if some are missing, the score is recomputed from the rest.' },
    src_live: { title: 'Status: live', body: 'Means the data was just fetched fresh from the real server.' },
    src_fallback: { title: 'Status: fallback', body: 'The primary server failed, so the data was fetched from a backup (alternate) server instead.' },
    src_cached: { title: 'Status: cached', body: 'The server could not be reached briefly, so the last saved data is shown temporarily.' },
    src_offline: { title: 'Status: offline', body: 'Could not fetch data. Check your internet or the server status and refresh.' },
  },
  ja: {
    score: { title: '買い時スコア', body: '下の6つの指標をまとめて作る0〜100点。高いほど「今は比較的買ってよい」、低いほど「過熱して買うには不利」という意味。未来を当てる予言ではなく、あくまで参考用の総合点だよ。' },
    RSI: { title: 'RSI・相対力指数', body: '最近の価格が上がりすぎ/下がりすぎかを0〜100で表す値。30より低いと「下がりすぎ(売られすぎ)」で反発が期待でき買い注目、70より高いと「上がりすぎ(買われすぎ)」で注意。' },
    MACD: { title: 'MACD・トレンドの勢い', body: '短期平均線と長期平均線の差で、価格が上がる「力」が強まるか弱まるかを見る。棒がマイナスから上に折れると、底からの反発開始のサインと読む。' },
    FNG: { title: '恐怖・強欲指数', body: '投資家が今こわがっている(恐怖)か欲をかいている(強欲)かを0〜100で測ったもの。0に近いとみんな怖がって売っている時で、逆にそこが安く買えるチャンスのことが多い(逆張り)。100に近いと過熱。' },
    Mayer: { title: 'マイヤー倍率', body: '今の価格が「200日平均価格」の何倍かを示す値。1より小さいと平均より安い、0.8以下なら歴史的に底値圏(強い買い)、2.4以上は割高な過熱とみる。' },
    DD: { title: '下落率・高値からの下げ', body: '直近1年の最高値から今、何%下がったか。-50%なら天井から半値。大きく下がるほど恐怖局面で、分割買いのチャンスとみる指標。' },
    GC_DC: { title: 'ゴールデン/デッドクロス', body: '短期平均線(50日)が長期平均線(200日)を上に抜けるとゴールデンクロス(上昇トレンド開始)、下に抜けるとデッドクロス(下落トレンド)。大きな流れが上向きか下向きかを見る。' },
    mcap: { title: '時価総額', body: 'コイン全体の市場価値。現在価格 × 流通枚数で計算する。そのコインが市場でどれくらい大きいかを表す。' },
    vol: { title: '出来高(24時間)', body: '直近24時間で売買された総額。多いほど人々の関心と取引が活発という意味。' },
    chg24: { title: '24時間変動率', body: '1日前と比べて価格が何%上がった(緑)・下がった(赤)かを表す。' },
    stale: { title: 'STALE・古いデータ', body: '取得したデータが古くて新鮮でないという表示。更新(↻)すると最新になる。' },
    coverage: { title: '指標カバレッジ', body: 'スコア計算時に6つの指標のうち何個が実際に生きているか。6/6なら全反映、欠けると残りだけで再計算する。' },
    src_live: { title: '状態: live', body: '今まさに実際のサーバーから取得した最新データという意味。' },
    src_fallback: { title: '状態: fallback', body: '1番目のサーバーが使えず、予備(別)のサーバーから代わりに取得したという意味。' },
    src_cached: { title: '状態: cached', body: '一時的にサーバーへ接続できず、保存しておいた直前のデータを仮表示中。' },
    src_offline: { title: '状態: offline', body: 'データを取得できなかった。ネットやサーバー状態を確認して更新してね。' },
  },
  ko: {
    score: { title: '매수 타이밍 점수', body: '아래 6개 지표를 한데 모아 만든 0~100점이야. 점수가 높을수록 "지금 사기 괜찮은 편", 낮을수록 "과열돼서 사기엔 부담"이라는 뜻. 미래를 맞히는 예언이 아니라 참고용 종합 점수야.' },
    RSI: { title: 'RSI · 상대강도지수', body: '최근 가격이 너무 빨리 올랐는지/떨어졌는지를 0~100으로 나타낸 값이야. 30보다 낮으면 "너무 많이 떨어졌다(과매도)"라 반등이 기대돼 매수 관심, 70보다 높으면 "너무 올랐다(과매수)"라 조심해야 해.' },
    MACD: { title: 'MACD · 추세 모멘텀', body: '단기 평균선과 장기 평균선의 차이로, 가격이 오르는 "힘"이 세지는지 약해지는지를 봐. 막대가 마이너스에서 위로 꺾이면 바닥에서 반등이 시작된다는 신호로 읽어.' },
    FNG: { title: '공포·탐욕 지수', body: '투자자들이 지금 무서워하는지(공포) 욕심내는지(탐욕)를 0~100으로 잰 거야. 0에 가까우면 다들 겁먹고 파는 중인데, 오히려 그때가 싸게 살 기회인 경우가 많아(역발상). 100에 가까우면 과열이야.' },
    Mayer: { title: 'Mayer Multiple · 마이어 배수', body: '지금 가격이 "200일 평균 가격"의 몇 배인지 나타낸 값이야. 1보다 작으면 평균보다 싸다는 뜻, 0.8 아래면 역사적으로 바닥권(강한 매수), 2.4 위면 너무 비싼 과열로 봐.' },
    DD: { title: '낙폭 · 고점 대비 하락률', body: '최근 1년 최고가에서 지금 몇 % 떨어졌는지야. -50%면 최고점에서 반토막 났다는 뜻. 많이 떨어졌을수록 공포 국면이라 분할 매수 기회로 보는 지표야.' },
    GC_DC: { title: '골든/데드 크로스', body: '단기 평균선(50일)이 장기 평균선(200일)을 위로 뚫으면 골든크로스(상승 추세 시작), 아래로 뚫으면 데드크로스(하락 추세)야. 큰 추세가 위쪽인지 아래쪽인지 보는 거야.' },
    mcap: { title: '시가총액(시총)', body: '코인 전체의 시장 가치야. 현재 가격 × 시중에 풀린 코인 수로 계산해. 그 코인이 시장에서 얼마나 큰지 보여줘.' },
    vol: { title: '거래량 (24시간)', body: '최근 24시간 동안 사고팔린 총 금액이야. 많을수록 사람들의 관심과 거래가 활발하다는 뜻.' },
    chg24: { title: '24시간 변동률', body: '하루 전과 비교해 가격이 몇 % 올랐는지(초록)·내렸는지(빨강)를 나타내.' },
    stale: { title: 'STALE · 오래된 데이터', body: '받아온 데이터가 너무 오래돼서 신선하지 않다는 표시야. 새로고침(↻)하면 최신으로 갱신돼.' },
    coverage: { title: '지표 커버리지', body: '점수를 계산할 때 6개 지표 중 몇 개가 실제로 살아있는지를 뜻해. 6/6이면 전부 반영, 일부가 빠지면 남은 것들로만 점수를 다시 계산해.' },
    src_live: { title: '데이터 상태: live', body: '방금 실제 서버에서 받아온 최신 데이터라는 뜻이야.' },
    src_fallback: { title: '데이터 상태: fallback', body: '1순위 서버가 안 돼서 예비(다른) 서버에서 대신 받아왔다는 뜻이야.' },
    src_cached: { title: '데이터 상태: cached', body: '잠시 서버를 못 불러와서, 저장해 둔 직전 데이터를 임시로 보여주는 중이야.' },
    src_offline: { title: '데이터 상태: offline', body: '데이터를 못 받아왔어. 인터넷이나 서버 상태를 확인하고 새로고침해봐.' },
  },
  zh: {
    score: { title: '买入时机评分', body: '把下面6个指标合在一起算出的0~100分。分数越高表示"现在买入相对还行"，越低表示"过热、买入有压力"。它不是预测未来，只是一个参考用的综合分。' },
    RSI: { title: 'RSI·相对强弱指数', body: '用0~100表示最近价格是否涨得/跌得太快。低于30="跌太多(超卖)"，有望反弹，可关注买入；高于70="涨太多(超买)"，要小心。' },
    MACD: { title: 'MACD·趋势动能', body: '用短期均线和长期均线之差，看上涨的"力量"在增强还是减弱。柱子从负值往上拐时，读作从底部开始反弹的信号。' },
    FNG: { title: '恐惧与贪婪指数', body: '用0~100衡量投资者现在是害怕(恐惧)还是贪婪。接近0时大家都在恐慌抛售，反而常常是便宜买入的机会(逆向)；接近100则是过热。' },
    Mayer: { title: 'Mayer倍数', body: '现在价格是"200日平均价"的几倍。小于1表示比平均便宜，0.8以下在历史上属于底部区(强力买入)，2.4以上视为过贵的过热。' },
    DD: { title: '回撤·相对高点跌幅', body: '从最近一年的最高价到现在跌了百分之几。-50%表示从顶部腰斩。跌得越多越属于恐慌阶段，被视为分批买入的机会。' },
    GC_DC: { title: '金叉/死叉', body: '短期均线(50日)上穿长期均线(200日)为金叉(上升趋势开始)，下穿为死叉(下降趋势)。用来看大趋势是向上还是向下。' },
    mcap: { title: '市值', body: '整个币的市场价值。用当前价格 × 流通数量计算。它显示这个币在市场中有多大。' },
    vol: { title: '成交量(24小时)', body: '最近24小时内买卖的总金额。越大表示人们的关注和交易越活跃。' },
    chg24: { title: '24小时涨跌幅', body: '与一天前相比价格涨了(绿)/跌了(红)百分之几。' },
    stale: { title: 'STALE·过期数据', body: '表示取到的数据太旧、不够新鲜。点刷新(↻)即可更新到最新。' },
    coverage: { title: '指标覆盖率', body: '计算评分时6个指标中实际有几个在线。6/6表示全部计入；若有缺失，则用其余指标重新计算。' },
    src_live: { title: '状态: live', body: '表示刚刚从真实服务器取到的最新数据。' },
    src_fallback: { title: '状态: fallback', body: '首选服务器不可用，改从备用(其他)服务器取到的数据。' },
    src_cached: { title: '状态: cached', body: '短暂无法访问服务器，暂时显示之前保存的数据。' },
    src_offline: { title: '状态: offline', body: '未能取到数据。请检查网络或服务器状态后刷新。' },
  },
  es: {
    score: { title: 'Puntuación de Timing de Compra', body: 'Una puntuación de 0 a 100 que combina los 6 indicadores de abajo. Más alta significa "momento relativamente OK para comprar"; más baja, "sobrecalentado, arriesgado comprar". No predice el futuro: es solo una referencia compuesta.' },
    RSI: { title: 'RSI · Índice de Fuerza Relativa', body: 'Muestra de 0 a 100 si el precio subió o bajó demasiado rápido. Por debajo de 30 = "cayó demasiado (sobreventa)", se espera rebote — interés de compra. Por encima de 70 = "subió demasiado (sobrecompra)" — cuidado.' },
    MACD: { title: 'MACD · Momentum de Tendencia', body: 'Usa la diferencia entre una media corta y una larga para ver si la "fuerza" alcista se refuerza o se debilita. Cuando las barras giran al alza desde lo negativo, se lee como un rebote desde el fondo.' },
    FNG: { title: 'Índice de Miedo y Codicia', body: 'Mide de 0 a 100 si los inversores tienen miedo o codicia. Cerca de 0 todos venden con pánico — a menudo la oportunidad barata de compra (contrario). Cerca de 100 está sobrecalentado.' },
    Mayer: { title: 'Múltiplo de Mayer', body: 'Cuántas veces está el precio actual respecto al "precio medio de 200 días". Por debajo de 1 = más barato que la media; por debajo de 0.8 = zona de suelo histórica (compra fuerte); por encima de 2.4 = sobrecalentado/caro.' },
    DD: { title: 'Caída · Bajada desde el Máximo', body: 'Cuántos % ha caído el precio desde el máximo del último año. -50% significa que se redujo a la mitad desde el techo. Cuanto mayor la caída, más se ve como fase de miedo y oportunidad de compra escalonada.' },
    GC_DC: { title: 'Cruce Dorado / de la Muerte', body: 'Cuando la media corta (50d) cruza por encima de la larga (200d) es cruce dorado (empieza tendencia alcista); por debajo es cruce de la muerte (bajista). Indica si la gran tendencia apunta arriba o abajo.' },
    mcap: { title: 'Capitalización de Mercado', body: 'El valor total de la moneda en el mercado. Se calcula como precio actual × monedas en circulación. Muestra cuán grande es la moneda en el mercado.' },
    vol: { title: 'Volumen (24h)', body: 'El importe total negociado en las últimas 24 horas. Cuanto mayor, más activo el interés y la negociación.' },
    chg24: { title: 'Cambio 24h', body: 'Cuántos % subió (verde) o bajó (rojo) el precio respecto a hace un día.' },
    stale: { title: 'STALE · Datos Antiguos', body: 'Una marca que indica que los datos son demasiado antiguos para estar frescos. Pulsa actualizar (↻) para ponerlos al día.' },
    coverage: { title: 'Cobertura de Indicadores', body: 'Cuántos de los 6 indicadores están realmente en línea al calcular la puntuación. 6/6 = todos usados; si faltan algunos, se recalcula con el resto.' },
    src_live: { title: 'Estado: live', body: 'Significa que los datos se acaban de obtener frescos del servidor real.' },
    src_fallback: { title: 'Estado: fallback', body: 'El servidor principal falló, así que los datos se obtuvieron de un servidor de respaldo (alternativo).' },
    src_cached: { title: 'Estado: cached', body: 'No se pudo acceder al servidor un momento, así que se muestran temporalmente los últimos datos guardados.' },
    src_offline: { title: 'Estado: offline', body: 'No se pudieron obtener datos. Revisa tu internet o el estado del servidor y actualiza.' },
  },
  fr: {
    score: { title: 'Score de Timing d’Achat', body: 'Un score de 0 à 100 combinant les 6 indicateurs ci-dessous. Plus haut = "moment relativement correct pour acheter" ; plus bas = "surchauffe, risqué d’acheter". Ce n’est pas une prédiction de l’avenir, juste une référence composite.' },
    RSI: { title: 'RSI · Indice de Force Relative', body: 'Indique de 0 à 100 si le prix est monté ou descendu trop vite. Sous 30 = "trop baissé (survente)", un rebond est attendu — intérêt à l’achat. Au-dessus de 70 = "trop monté (surachat)" — prudence.' },
    MACD: { title: 'MACD · Momentum de Tendance', body: 'Utilise l’écart entre une moyenne courte et une longue pour voir si la "force" haussière se renforce ou faiblit. Quand les barres remontent depuis le négatif, on lit un rebond depuis le creux.' },
    FNG: { title: 'Indice Peur & Avidité', body: 'Mesure de 0 à 100 si les investisseurs ont peur ou sont avides. Près de 0, tout le monde vend dans la panique — souvent l’occasion d’acheter pas cher (à contre-courant). Près de 100, c’est la surchauffe.' },
    Mayer: { title: 'Multiple de Mayer', body: 'Combien de fois le prix actuel vaut le "prix moyen sur 200 jours". Sous 1 = moins cher que la moyenne ; sous 0.8 = zone de plancher historique (achat fort) ; au-dessus de 2.4 = surchauffe/cher.' },
    DD: { title: 'Repli · Baisse depuis le Sommet', body: 'De combien de % le prix a baissé depuis le plus haut de l’année. -50% = divisé par deux depuis le sommet. Plus la baisse est forte, plus c’est vu comme une phase de peur et une occasion d’achat échelonné.' },
    GC_DC: { title: 'Croix Dorée / de la Mort', body: 'Quand la moyenne courte (50j) passe au-dessus de la longue (200j), c’est une croix dorée (début de tendance haussière) ; en dessous, une croix de la mort (baissière). Montre si la grande tendance pointe vers le haut ou le bas.' },
    mcap: { title: 'Capitalisation', body: 'La valeur totale de la pièce sur le marché. Calculée comme prix actuel × pièces en circulation. Montre la taille de la pièce sur le marché.' },
    vol: { title: 'Volume (24h)', body: 'Le montant total échangé sur les dernières 24 heures. Plus il est élevé, plus l’intérêt et les échanges sont actifs.' },
    chg24: { title: 'Variation 24h', body: 'De combien de % le prix a monté (vert) ou baissé (rouge) par rapport à la veille.' },
    stale: { title: 'STALE · Données Anciennes', body: 'Un indicateur signalant que les données récupérées sont trop anciennes. Appuyez sur actualiser (↻) pour les mettre à jour.' },
    coverage: { title: 'Couverture des Indicateurs', body: 'Combien des 6 indicateurs sont réellement en ligne lors du calcul du score. 6/6 = tous utilisés ; s’il en manque, le score est recalculé avec le reste.' },
    src_live: { title: 'État : live', body: 'Signifie que les données viennent d’être récupérées fraîches depuis le vrai serveur.' },
    src_fallback: { title: 'État : fallback', body: 'Le serveur principal a échoué, les données ont donc été récupérées depuis un serveur de secours (alternatif).' },
    src_cached: { title: 'État : cached', body: 'Le serveur était brièvement injoignable, on affiche temporairement les dernières données enregistrées.' },
    src_offline: { title: 'État : offline', body: 'Impossible de récupérer les données. Vérifiez votre connexion ou l’état du serveur et actualisez.' },
  },
}
